export default {
  A: { args: ['rx', 'ry', 'rotation', 'arc', 'sweep', 'ex', 'ey'] },
  a: { args: ['rx', 'ry', 'rotation', 'arc', 'sweep', 'ex', 'ey'] },
  C: { args: ['cx1', 'cy1', 'cx2', 'cy2', 'ex', 'ey'] },
  c: { args: ['cx1', 'cy1', 'cx2', 'cy2', 'ex', 'ey'] },
  H: { args: ['x'] },
  h: { args: ['x'] },
  L: { args: ['x', 'y'] },
  l: { args: ['x', 'y'] },
  M: { args: ['x', 'y'] },
  m: { args: ['x', 'y'] },
  Q: { args: ['cx', 'cy', 'ex', 'ey'] },
  q: { args: ['cx', 'cy', 'ex', 'ey'] },
  S: { args: ['cx', 'cy', 'ex', 'ey'] },
  s: { args: ['cx', 'cy', 'ex', 'ey'] },
  T: { args: ['ex', 'ey'] },
  t: { args: ['ex', 'ey'] },
  V: { args: ['y'] },
  v: { args: ['y'] },
  z: { args: [] },
};
